version: 2
jobs:
  link_check:
    branches:
      ignore:
        - master
    docker:
      - image: posworkshop84/golang-hugo-ci:v1
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Pull in submodule"
          command: git submodule update --init --recursive
      - run:
          name: "Build site"
          command: make build_local
      - run:
          name: "Link check"
          command: make html_linkcheck
